### ISSUE TITLE
Controller Actions do not handle Protobufs Timestamps correctly

### ISSUE THREAD

**Issue by campbellwray** [Havret/Protobuf.System.Text.Json#59]
## Describe the bug 
I have a Web API project in which I have added [Protobuf.System.Text.Json](https://github.com/Havret/Protobuf.System.Text.Json) support to the Controllers by adding the following to `Program.cs`

```
builder.Services.AddControllers().AddJsonOptions(options =>
{
    options.JsonSerializerOptions.AddProtobufSupport();
});
```

I have also set up a simple controller action
```
[HttpGet]
public ActionResult<Timestamp> GetTimestamp ([FromQuery] Timestamp t)
{
    return t;
}
```

When viewing the endpoint through Swagger the Timestamp fields are incorrectly interpreted as `Seconds`/`Nanos`

![image](https://user-images.githubusercontent.com/9245142/236211138-9b0eaa67-f60d-4408-8e5e-1b1e13535ecd.png)

Which means that I cannot pass a Timestamp in the RFC 3339 format (`2023-04-03T18:19:31.567Z`)

If however I pass `Seconds`/`Nanos`, the returned Timestamp is in the expected format.

![image](https://user-images.githubusercontent.com/9245142/236212069-0ec0cdcb-d53b-4ece-ac10-eae1c5530443.png)
![image](https://user-images.githubusercontent.com/9245142/236212025-ce01c4c8-c114-4adb-8a01-41e5d84fec18.png)

If I try to use Postman/Curl to forcibly pass Timestamps in this format the resulting property `t` is null.

It seems that there is some kind of conflict somewhere with .NETs Model Binder, Swagger or something else Web API related, `Timestamp` objects are being serialized correctly, but the deserialization has a bug.

## Expected behavior

1. The Controller endpoint should accept datetime strings.
2. It should be possible to use Swagger to send datetime strings.

## Environment:

- OS: Windows 11
- Version: 1.2.0
- .NET Version: 7

## Additional context
None

**Comment by campbellwray** [comment]
Sorry for the slow reply, and thank you for all the information.

I was able to solve my issue with a mixture of a `TypeConverter`, to convert the `date-time` string to a `Timestamp`, and the `SwaggerGen` option `options.MapType<Timestamp>(() => new OpenApiSchema { Type = "string", Format = "date-time" });`

I didn't end up needing a Schema Filter in the end, and the TypeConverter was much more versatile than a custom Model binder, as it only needed to be defined once, rather than manually specifying the custom model binder any time I used a Timestamp in my API.

**Comment by Havret** [comment]
@campbellwray, that looks like a really neat solution. `MapType` seems to be much better suited for this than a custom schema filter, which I've used so far to address the issue. You live and learn! Thanks for sharing this.
